name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.key }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      # Deploy
      - run: ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no ${{ secrets.user }}@${{ secrets.ip }} 'export PATH="/home/${{ secrets.user }}/.nvm/versions/node/v16.13.1/bin:$PATH"; (pm2 delete index) || :; cd ~/bot/; rm -rf 5/*; (mv 4/* 5/) || :; (mv 3/* 4/) || :; (mv 2/* 3/) || :; (mv 1/* 2/) || :'
      - run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . ${{ secrets.user }}@${{ secrets.ip }}:~/bot/1/
      - run: ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no ${{ secrets.user }}@${{ secrets.ip }} 'export PATH="/home/${{ secrets.user }}/.nvm/versions/node/v16.13.1/bin:$PATH"; cd ~/bot/1/src/; npm ci; NODE_ENV=${{ secrets.node_env }} TOKEN=${{ secrets.token }} DB_URL=${{ secrets.db_url }} BOT_ID=${{ secrets.bot_id }} pm2 start index.js'
